### ISSUE TITLE
ModuleNotFoundError due to naming mismatch

### ISSUE THREAD

**Issue by dyanni3** [getnamo/machine-learning-remote-ue4#4]
In the ml-remote-server directory downloaded from latest release there is a file mlPluginApi.py, but all the example scripts in the scripts directory try to import mlpluginapi leading to a module not found error. Fix could be to simply rename the mlPluginApi.py to mlpluginapi.py or alternately change all the import statements. I'm happy to do this later today!

`connect  264388b508714e0f848ffd1e9f77fb38
loading <hello.py>
hello import
Task exception was never retrieved
future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\dyanni\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\asyncio_server.py:437> exception=ModuleNotFoundError("No module named 'mlpluginapi'")>
Traceback (most recent call last):
  File "C:\Users\dyanni\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\asyncio_server.py", line 438, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\dyanni\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\asyncio_server.py", line 466, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "server.py", line 80, in start_script
    valid, err = mlp.load(script_name)
  File "C:\Users\dyanni\Desktop\ml_remote\ml-remote-server\mlplugin.py", line 33, in load
    active_script = importlib.import_module(script_folder + '.' + script_name)
  File "C:\Users\dyanni\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\dyanni\Desktop\ml_remote\ml-remote-server\scripts\hello.py", line 3, in <module>
    from mlpluginapi import MLPluginAPI
ModuleNotFoundError: No module named 'mlpluginapi'
disconnect 264388b508714e0f848ffd1e9f77fb38`

**Comment by getnamo** [comment]
I think using 'mlpluginapi.py' is the pep appropriate approach. If you do fix it, I'll merge any pull requests

**Comment by dyanni3** [comment]
Thanks, PR is over at ml-remote-server.

**Comment by getnamo** [comment]
merged, thanks for the fix :)
